# Generated by Django 5.0.3 on 2024-03-31 22:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('neighborhood', models.CharField(choices=[('El-Finesh', 'El-Finesh'), ('El-Ubeid', 'El-Ubeid'), ('zone 8', 'zone 8'), ('zone 3', 'zone 3'), ('zone 5', 'zone 5'), ('ElQussasi', 'ElQussasi'), ('Abu jafar', 'Abu jafar'), ('zone 6', 'zone 6'), ('Abu Hani', 'Abu Hani'), ('El Ubra', 'El Ubra'), ('El jalawi', 'El jalawi'), ('El Qrinawi', 'El Qrinawi'), ('zone 4', 'zone 4'), ('El katnani', 'El katnani'), ('Abu bilal', 'Abu bilal'), ('29', '29'), ('27', '27'), ('21', '21'), ('25', '25'), ('12', '12'), ('23', '23'), ('15', '15'), ('19', '19')], max_length=15)),
                ('Facility', models.CharField(choices=[('Healthcare Deficiency', 'Healthcare Deficiency'), ('Transportation Weakness', 'Transportation Weakness'), ('Electricity Service Center', 'Electricity Service Center'), ('Water Treatment Plant', 'Water Treatment Plant'), ('Road Maintenance Workshop', 'Road Maintenance Workshop'), ('Street Lighting Facility', 'Street Lighting Facility'), ('Environmental Conservation Hub', 'Environmental Conservation Hub'), ('Animal Control Facility', 'Animal Control Facility')], max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(max_length=500)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'addreport',
            },
        ),
        migrations.CreateModel(
            name='AssignedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.BooleanField(default=False)),
                ('reportnumber', models.IntegerField()),
                ('reports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.addreport')),
            ],
        ),
        migrations.CreateModel(
            name='citezinreports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reportnumber', models.IntegerField(default=0)),
                ('reports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.addreport')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reportnumber', models.IntegerField()),
                ('reports', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.addreport')),
            ],
            options={
                'db_table': 'managerreports',
            },
        ),
    ]
