# Generated by Django 5.0.3 on 2024-04-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_addreport_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addreport',
            name='Facility',
        ),
        migrations.AddField(
            model_name='addreport',
            name='facility',
            field=models.CharField(choices=[('Healthcare Deficiency', 'Healthcare Deficiency'), ('Transportation Weakness', 'Transportation Weakness'), ('Electricity Service Center', 'Electricity Service Center'), ('Water Treatment Plant', 'Water Treatment Plant'), ('Road Maintenance Workshop', 'Road Maintenance Workshop'), ('Street Lighting Facility', 'Street Lighting Facility'), ('Environmental Conservation Hub', 'Environmental Conservation Hub'), ('Animal Control Facility', 'Animal Control Facility'), ('Traffic', 'Traffic'), ('other', 'other')], default='', max_length=150),
        ),
    ]
